apiVersion: v1
kind: Service
metadata:
  name: cl-tech-v1-service
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
