name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Устанавливаем Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Собираем Docker-образ
      - name: Build Docker image
        run: |
          docker build . -t aantoshechkin/cltech:${{ github.sha }}

      # Пушим Docker-образ в Docker Hub
      - name: Push Docker image
        run: |
          docker push aantoshechkin/cltech:${{ github.sha }}